### ISSUE TITLE
Is there a way to import all db.models for my shell?

### ISSUE THREAD

**Issue by rlam3** [smurfix/flask-script#147]
Is there a way to import all db.models for my shell when going interactive shell? I'm using sqlalchemy.

I'm using make_context and only able to pass models into the dictionary.... I want to be able to use the shell without having to do 

```` 

from app.models.user import User 
etc...
````

every time I go into interactive shell

Thanks!

**Comment by davidism** [comment]
`db.Model._decl_class_registry` contains a weak reference mapping names to models.  You can use the [`shell`][1] decorator to define your own context that includes all these.

[1]: https://flask-script.readthedocs.org/en/latest/#shell

**Comment by jeffwidman** [comment]
FWIW, here's how I handle auto-imports of my models when I run `python manage.py shell`:

    app = create_app(os.getenv('FLASK_CONFIG') or 'default')
    manager = Manager(app)

    def make_shell_context():
        from pprint import pprint
        from flask_sqlalchemy import get_debug_queries
        return dict(
            app=app, db=db,
            pprint=pprint, gq=get_debug_queries,
            Article=Article,
            ArticleCategory=ArticleCategory,
            ArticleComment=ArticleComment)
            
    manager.add_command('shell', Shell(make_context=make_shell_context))

Works fine for me

**Comment by plaes** [comment]
Jeff's example should end up in docs.

**Comment by rlam3** [comment]
@jeffwidman this would mean that if my models are in different folders, i would have to import them individually. I was hoping to import all models from a model folder and then each class within each module... more like a for loop

**Comment by jeffwidman** [comment]
I agree it's a pain. My wife was working on a somewhat similar problem recently around looping through `imports` and found the stdlib `importlib` useful. Afraid I haven't zero experience with it myself, so can't comment, but if you do explore and figure out a way to get it working, I'm definitely open to a PR putting an example in the docs.

**Comment by hectorcanto** [comment]
Just if somebody ends up here and don't know how to import shell
```python
from flask_script import Shell
```
> FWIW, here's how I handle auto-imports of my models when I run `python manage.py shell`:
> 
> ```
> app = create_app(os.getenv('FLASK_CONFIG') or 'default')
> manager = Manager(app)
> 
> def make_shell_context():
>     from pprint import pprint
>     from flask_sqlalchemy import get_debug_queries
>     return dict(
>         app=app, db=db,
>         pprint=pprint, gq=get_debug_queries,
>         Article=Article,
>         ArticleCategory=ArticleCategory,
>         ArticleComment=ArticleComment)
> 
> manager.add_command('shell', Shell(make_context=make_shell_context))
> ```
> 
> Works fine for me

**Comment by FilippoLippi** [comment]
if someone would like to import all models from a package:

```python
import inspect
from app import db, models

def make_shell_context():
    return dict(
        db=db,
        **dict(inspect.getmembers(models, inspect.isclass)))
```
