### ISSUE TITLE
Support ptpython for shell

### ISSUE THREAD

**Issue by hongquan** [smurfix/flask-script#148]
Please support [ptpython](https://github.com/jonathanslenders/ptpython/) for `./manage.py shell` command.

Quick look of ptpython feature:

![ptpython](https://raw.githubusercontent.com/jonathanslenders/ptpython/master/docs/images/example1.png)

**Comment by jeffwidman** [comment]
Fixed in #153

**Comment by jace** [comment]
Looks like this change hasn't made it to PyPI yet. [No update there since 2014](https://pypi.python.org/pypi/Flask-Script). What is the recommended way to use this feature?
