### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by rlam3** [smurfix/flask-script#149]
New release?

**Comment by jeffwidman** [comment]
@smurfix can you add me as a collaborator on Pypi so I can push a new release once #44 is fixed? I'm 'jeffwidman' over there.

**Comment by smurfix** [comment]
done

On 21.02.2016 22:52, Jeff Widman wrote:
>
> @smurfix <https://github.com/smurfix> can you add me as a collaborator
> on Pypi so I can push a new release once #44
> <https://github.com/smurfix/flask-script/issues/44> is fixed? I'm
> 'jeffwidman' over there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/smurfix/flask-script/issues/149#issuecomment-186925880>.
>


-- 
-- Matthias Urlichs

**Comment by anthraxx** [comment]
2.0.6 is on github and pypi
