### ISSUE TITLE
Is there a way for flask-script to skip certain files/folders for detecting changes?

### ISSUE THREAD

**Issue by rlam3** [smurfix/flask-script#162]
Is there a way for flask-script to skip certain files/folders for detecting changes?

I'm trying to use wercker CI with my project... However flask-script seems to be taking 60+seconds to detect changes of my files because of the several folders that wercker-cli has created. And this is really annoying and having to wait this long to detect changes. Is there a way for flask-script to skip these files/folders?

The following is the command using the server class from flask-script

```

manager.add_command("runserver",
    Server(
        threaded=True,
        use_reloader=True,
        use_debugger=True,
        host='0.0.0.0',
        port=5000,
    )
)

```

Thanks!

**Comment by jeffwidman** [comment]
Please use StackOverflow for support questions, the issue tracker is for bugs. Thanks.
