### ISSUE TITLE
Terminal said no module named flask_script

### ISSUE THREAD

**Issue by Insofan** [smurfix/flask-script#173]
I using python 2.7 and installed Flask-Script but when i run it it said no module named flask_script
   ```
 python MyBlog.py
Traceback (most recent call last):
  File "MyBlog.py", line 2, in <module>
    from flask_script import Manager
ImportError: No module named flask_script
```

and sub is MyBlog.py
 ````
from flask import Flask
from flask_script import Manager
app = Flask(__name__)
manager = Manager(app)

@app.route('/')
def hello_world():
    return 'Hello World!'


if __name__ == '__main__':
    manager.run()`
```

**Comment by alexcushing** [comment]
I get this too, did you ever figure it out?

**Comment by jeffwidman** [comment]
Did you ever install Flask Script? Sounds like python can't find the module.

**Comment by essie-chams** [comment]
type  pip install Flask-Script. my assumption is its in the virtual environment. what will differ is the python version. if it was installed in python2 and you trying running it in python3, it will definitely give an error message
