### ISSUE TITLE
Could we get a new release ?

### ISSUE THREAD

**Issue by dmsimard** [smurfix/flask-script#174]
Last release of flask-script, [2.0.3](https://github.com/smurfix/flask-script/releases/tag/v2.0.3) was in May 2014 and there has been 62 commits since then.

I'm particularly interested in the bugfix for https://github.com/smurfix/flask-script/issues/102 which was merged in 2015.

Appreciate it,

Thanks !

**Comment by sobolevn** [comment]
@smurfix @jeffwidman any progress?

**Comment by SirScott** [comment]
A release sure would be nice!  Looking for #150 personally.

**Comment by AlJohri** [comment]
pinging @jeffwidman

**Comment by anthraxx** [comment]
same here, please tag that thingie :yum: 
@smurfix @jeffwidman

**Comment by jeffwidman** [comment]
I'm really not actively maintaining this other than merging PR's so that those who want to follow master don't have to have a gazillion patches applied after the fact.

For an actual release, please ping @smurfix. 

Personally, I recommend migrating to the new Flask CLI that is based on Click, as it seems @smurfix has pretty much abandoned this project.

**Comment by smurfix** [comment]
if anybody cares to do a release I'd be happy to grant write access to this repository.

**Comment by anthraxx** [comment]
Well, I could do a release, and if wanted keep an eye on this and regularly do so. 
I'm an Arch Linux package maintainer and need this for other dependencies, namely flask-migrate f.e.

Cheers

**Comment by davidism** [comment]
@anthraxx Flask-Migrate supports the built-in Flask CLI. Arch packages the latest Flask version. You shouldn't need Flask-Script for that.

**Comment by anthraxx** [comment]
@smurfix thanks for the trust, i will tag a release of the current HEAD within the next days. Should I also keep an eye on some pull requests and bug reports?

**Comment by anthraxx** [comment]
@davidism I see, i will do some tests how things work out without. however i will still try to keep a small portion of time to do stuff over here.

**Comment by smurfix** [comment]
Sure, please do.

**Comment by AlJohri** [comment]
@anthraxx might want to also add a note to the README noting that a built-in flask cli exists

**Comment by anthraxx** [comment]
@smurfix  I have pushed a 2.0.6 tag, how do we get this to pypi?

**Comment by smurfix** [comment]
I'm sure I can give you upload rights if you tell me your pypi ID.

**Comment by anthraxx** [comment]
@smurfix 
Username: anthraxx

thanks

**Comment by smurfix** [comment]
@anthraxx  Done, you're free to upload.

**Comment by anthraxx** [comment]
2.0.6 has been released on github and pypi
