### ISSUE TITLE
Update documentation for threading/processes.

### ISSUE THREAD

**Issue by rduplain** [smurfix/flask-script#32]
From #30, @ThomasWaldmann notes:

> As IE and chrome incognito mode seem to have a similar behaviour, you just made these users happy. Well, in case they find out that they have to use these options... - maybe it should be documented somewhere (where?) that one should try --threaded or --processes N if one experiences a "hanging" server. It maybe also should be documented that a non-threaded / single process server is easier for debugging purposes.

**Comment by jeffwidman** [comment]
This issue is pretty old, so I'm closing. If still a problem relevant to the current release, please comment and we can re-open.
