### ISSUE TITLE
Exception KeyError: KeyError(4414541008,) in <module 'threading'

### ISSUE THREAD

**Issue by kirs** [smurfix/flask-script#48]
After I run any flash CLI script, I get this:

```
Exception KeyError: KeyError(4414541008,) in <module 'threading' from '/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.pyc'> ignored
```

I have Python 2.7.3 installed from Brew on my OS X 10.8.

**Comment by kxxoling** [comment]
Same 'error'. I get it out after removing the monkey patching code, turns out no error.
What I did wrong is I forgot to add ``manager.run()``, sigh!
