### ISSUE TITLE
Add support for alternate formatting classes 

### ISSUE THREAD

**Issue by croach** [smurfix/flask-script#61]
Currently, Flask-Script ignores all whitespace formatting when displaying help text for a command. It would be great if we could specify which one of the argparse formatter classes to use in formatting the help text.

Currently I have help text for my command and it prints out like the following:

    Send out email task reminders to active employees If the threshold argument is
    None (the default), the total percentage of the company about to be emailed
    will be printed and the user will be prompted as to whether or not they wish
    to continue. When set to a value, it must be set to a decimal value equal to
    or less than 1.0. If greater than or equal to 0.0, the percentage of people to
    be emailed will be checked against the threshold value and if it doesn't
    exceed it, the emails will be sent. Setting the value to a negative number,
    turns off threshold checking completely. So, when running non-interactively
    (i.e., as a cron job) the threshold argument must be set. Examples: Set the
    threshold to 50% of the company: ./bin/cron-jobs send_task_reminders -t 0.5
    Turn threshold checking off: ./bin/cron-jobs send_task_reminders -t -1 Keyword
    Arguments: username -- the user to notify threshold -- the percentage of the
    company below which we can safely email

When really it should look like the following if I add the formatter_class argument to the argparse.ArgumentParser constructor and give it either argarse.RawTextHelpFormatter or argparse.ArgumentDefaultsHelpFormatter.

    Send out email task reminders to active employees

      If the threshold argument is None (the default), the total percentage of the
      company about to be emailed will be printed and the user will be prompted as
      to whether or not they wish to continue. When set to a value, it must be set
      to a decimal value equal to or less than 1.0. If greater than or equal to 0.0,
      the percentage of people to be emailed will be checked against the threshold
      value and if it doesn't exceed it, the emails will be sent. Setting the value
      to a negative number, turns off threshold checking completely. So, when
      running non-interactively (i.e., as a cron job) the threshold argument must
      be set.

      Examples:

        Set the threshold to 50% of the company:

          ./bin/cron-jobs send_task_reminders -t 0.5

        Turn threshold checking off:

          ./bin/cron-jobs send_task_reminders -t -1

      Keyword Arguments:
        username -- the user to notify
        threshold -- the percentage of the company below which we can safely email

**Comment by jeffwidman** [comment]
@croach clearing out old issues... is this still a problem?

**Comment by jeffwidman** [comment]
Closing for now, if this is still an issue, please comment and we can re-open.
