### ISSUE TITLE
The debug option does not work

### ISSUE THREAD

**Issue by st3fan** [smurfix/flask-script#63]
When starting a server with `runserver -d` the Flask app is not actually put in debug mode. The option is not transferred to `app.debug`. The reload option `-r` is though.

**Comment by CTACyok** [comment]
I have just the same issue here: the server won't run in debug mode, unless it's stated as "DEBUG = True" in config.py.
Flask 0.11.1
Flask-Script 2.0.5

**Comment by CTACyok** [comment]
The problem seems to be in class flask_script.commands.Server in method __run__
The second if statement should be
        if use_reloader is None:
            use_reloader = use_debugger
and now everything works fine.
Please update asap.
